/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import conta.PessoaFisica;
import conta.PessoaJuridica;
import javax.swing.JOptionPane;
import persistencia.controlador;

/**
 *
 * @author pabri
 */
public class abrir_nova_conta extends javax.swing.JFrame {
    controlador controlador;
    /**
     * Creates new form abrir_nova_conta
     */
    public abrir_nova_conta(controlador controlador) {
        this.controlador = controlador;
        initComponents();
        pane_pessoa_juridica.setVisible(false);
        pane_pessoa_fisica.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rb_pessoa_fisica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rb_pessoa_juridica = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        pane_pessoa_fisica = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_cpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_telefone_pessoa_fisica = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_endereco_pessoa_fisica = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_senha_pessoa_fisica = new javax.swing.JTextField();
        btn_cadastrar_pessoa_fisica = new javax.swing.JButton();
        pane_pessoa_juridica = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_cnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_razao_social = new javax.swing.JTextField();
        tf_telefone_pessoa_juridica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_endereco_pessoa_juridica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_senha_pessoa_juridica = new javax.swing.JTextField();
        btn_cadastrar_pessoa_juridica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(rb_pessoa_fisica);
        rb_pessoa_fisica.setText("Fisica ");
        rb_pessoa_fisica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_pessoa_fisicaStateChanged(evt);
            }
        });
        rb_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_pessoa_fisicaActionPerformed(evt);
            }
        });
        rb_pessoa_fisica.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                rb_pessoa_fisicaVetoableChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nova conta");

        buttonGroup1.add(rb_pessoa_juridica);
        rb_pessoa_juridica.setText("Juridica");
        rb_pessoa_juridica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rb_pessoa_juridicaStateChanged(evt);
            }
        });
        rb_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_pessoa_juridicaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de pessoa");

        jLabel8.setText("CPF");

        jLabel9.setText("Nome completo");

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefone");

        tf_telefone_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefone_pessoa_fisicaActionPerformed(evt);
            }
        });

        jLabel12.setText("Endereço");

        tf_endereco_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_endereco_pessoa_fisicaActionPerformed(evt);
            }
        });

        jLabel13.setText("Senha");

        tf_senha_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senha_pessoa_fisicaActionPerformed(evt);
            }
        });

        btn_cadastrar_pessoa_fisica.setText("cadastrar");
        btn_cadastrar_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_pessoa_fisicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_pessoa_fisicaLayout = new javax.swing.GroupLayout(pane_pessoa_fisica);
        pane_pessoa_fisica.setLayout(pane_pessoa_fisicaLayout);
        pane_pessoa_fisicaLayout.setHorizontalGroup(
            pane_pessoa_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_pessoa_fisicaLayout.createSequentialGroup()
                .addGroup(pane_pessoa_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_pessoa_fisicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pane_pessoa_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tf_telefone_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(tf_endereco_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tf_senha_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(pane_pessoa_fisicaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_cadastrar_pessoa_fisica)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        pane_pessoa_fisicaLayout.setVerticalGroup(
            pane_pessoa_fisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_pessoa_fisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_telefone_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_endereco_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_senha_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cadastrar_pessoa_fisica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("CNPJ");

        tf_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cnpjActionPerformed(evt);
            }
        });

        jLabel4.setText("Razão social");

        tf_razao_social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_razao_socialActionPerformed(evt);
            }
        });

        tf_telefone_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefone_pessoa_juridicaActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone");

        tf_endereco_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_endereco_pessoa_juridicaActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço");

        jLabel7.setText("Senha");

        tf_senha_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senha_pessoa_juridicaActionPerformed(evt);
            }
        });

        btn_cadastrar_pessoa_juridica.setText("cadastrar");
        btn_cadastrar_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_pessoa_juridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_pessoa_juridicaLayout = new javax.swing.GroupLayout(pane_pessoa_juridica);
        pane_pessoa_juridica.setLayout(pane_pessoa_juridicaLayout);
        pane_pessoa_juridicaLayout.setHorizontalGroup(
            pane_pessoa_juridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_pessoa_juridicaLayout.createSequentialGroup()
                .addGroup(pane_pessoa_juridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_pessoa_juridicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pane_pessoa_juridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tf_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tf_telefone_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tf_endereco_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(tf_senha_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pane_pessoa_juridicaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_cadastrar_pessoa_juridica)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        pane_pessoa_juridicaLayout.setVerticalGroup(
            pane_pessoa_juridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_pessoa_juridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_telefone_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_endereco_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_senha_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_cadastrar_pessoa_juridica)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pane_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_pessoa_fisica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb_pessoa_juridica))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_pessoa_fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_pessoa_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_pessoa_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_pessoa_fisicaActionPerformed

    private void rb_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_pessoa_juridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_pessoa_juridicaActionPerformed

    private void rb_pessoa_fisicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_pessoa_fisicaStateChanged
        // TODO add your handling code here:
        if (rb_pessoa_fisica.isSelected()){
           pane_pessoa_juridica.setVisible(false);
           pane_pessoa_fisica.setVisible(true);
        }
    }//GEN-LAST:event_rb_pessoa_fisicaStateChanged

    private void rb_pessoa_fisicaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_rb_pessoa_fisicaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_pessoa_fisicaVetoableChange

    private void rb_pessoa_juridicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rb_pessoa_juridicaStateChanged
        if (rb_pessoa_juridica.isSelected()){
           pane_pessoa_juridica.setVisible(true);
           pane_pessoa_fisica.setVisible(false);
        }
                   // TODO add your handling code here:
    }//GEN-LAST:event_rb_pessoa_juridicaStateChanged

    private void tf_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cnpjActionPerformed

    private void tf_razao_socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_razao_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_razao_socialActionPerformed

    private void tf_telefone_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefone_pessoa_juridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefone_pessoa_juridicaActionPerformed

    private void tf_endereco_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_endereco_pessoa_juridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_endereco_pessoa_juridicaActionPerformed

    private void tf_senha_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senha_pessoa_juridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senha_pessoa_juridicaActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_telefone_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefone_pessoa_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefone_pessoa_fisicaActionPerformed

    private void tf_endereco_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_endereco_pessoa_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_endereco_pessoa_fisicaActionPerformed

    private void tf_senha_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senha_pessoa_fisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senha_pessoa_fisicaActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void btn_cadastrar_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_pessoa_fisicaActionPerformed
    String end = tf_endereco_pessoa_fisica.getText();
    String tel = tf_telefone_pessoa_fisica.getText();
    String cnpj = tf_cpf.getText();
    String rs = tf_nome.getText();
    String s = tf_senha_pessoa_fisica.getText();
    PessoaFisica novaPessoa = new PessoaFisica(end, tel, cnpj, rs );
    novaPessoa.getConta().AbrirConta(s);
    controlador.listaPessoaFisica.add(novaPessoa);  
    JOptionPane.showMessageDialog(null, " Conta cadastrada com sucesso");
    this.dispose();
    }//GEN-LAST:event_btn_cadastrar_pessoa_fisicaActionPerformed

    private void btn_cadastrar_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_pessoa_juridicaActionPerformed
String end = tf_endereco_pessoa_juridica.getText();
String tel = tf_telefone_pessoa_juridica.getText();
String cnpj = tf_cnpj.getText();
String rs = tf_razao_social.getText();
String s = tf_senha_pessoa_juridica.getText();
 PessoaJuridica novaPessoa = new PessoaJuridica(end, tel, cnpj, rs );
 novaPessoa.getConta().AbrirConta(s);
 controlador.listaPessoaJuridica.add(novaPessoa);
 JOptionPane.showMessageDialog(null, " Conta cadastrada com sucesso");
 
    this.dispose();
    }//GEN-LAST:event_btn_cadastrar_pessoa_juridicaActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_pessoa_fisica;
    private javax.swing.JButton btn_cadastrar_pessoa_juridica;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pane_pessoa_fisica;
    private javax.swing.JPanel pane_pessoa_juridica;
    private javax.swing.JRadioButton rb_pessoa_fisica;
    private javax.swing.JRadioButton rb_pessoa_juridica;
    private javax.swing.JTextField tf_cnpj;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_endereco_pessoa_fisica;
    private javax.swing.JTextField tf_endereco_pessoa_juridica;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_razao_social;
    private javax.swing.JTextField tf_senha_pessoa_fisica;
    private javax.swing.JTextField tf_senha_pessoa_juridica;
    private javax.swing.JTextField tf_telefone_pessoa_fisica;
    private javax.swing.JTextField tf_telefone_pessoa_juridica;
    // End of variables declaration//GEN-END:variables
}
